'use strict';
const initial={houses:[{id:1,name:'Haus am Park',address:'Beispielstraße 12 · Nürnberg'},{id:2,name:'Haus an der Linde',address:'Musterweg 8 · Fürth'}],units:[{id:1,house:1,name:'Wohnung 1 · Erdgeschoss',area:65,tenant:'Erika Beispiel',rent:650,advance:180,deposit:1950},{id:2,house:1,name:'Wohnung 2 · Obergeschoss',area:85,tenant:'Karl Mustermann',rent:850,advance:220,deposit:2550},{id:3,house:2,name:'Wohnung 1 · Erdgeschoss',area:72,tenant:'Maria Muster',rent:720,advance:190,deposit:2160}],payments:[{unit:1,month:'2026-09',amount:830},{unit:2,month:'2026-09',amount:500}],bills:[{house:1,date:'2026-06-30',kind:'Wasserversorgung',amount:900},{house:1,date:'2026-07-01',kind:'Müllentsorgung',amount:600},{house:1,date:'2026-08-15',kind:'Gebäudereinigung',amount:1200},{house:2,date:'2026-07-01',kind:'Müllentsorgung',amount:450}]};
let data=structuredClone(initial),history=[],view='home',houseId=1,unitId=1,month='2026-09',step=1,year=2026,actualAdvance=0;
const app=document.getElementById('app'),money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const house=()=>data.houses.find(h=>h.id===houseId),unit=()=>data.units.find(u=>u.id===unitId),paid=u=>data.payments.filter(p=>p.unit===u.id&&p.month===month).reduce((s,p)=>s+p.amount,0);
function save(){history.push(structuredClone(data));document.getElementById('undo').disabled=false;document.getElementById('message').textContent='Änderung für diese Vorschau übernommen.';}
function go(v){view=v;render();window.scrollTo(0,0);const title=app.querySelector('h1');title?.setAttribute('tabindex','-1');title?.focus({preventScroll:true});}
function back(v='home'){return `<button class="back" data-go="${v}">← Zurück</button>`;}
function options(items,selected){return items.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${escape(x.name)}</option>`).join('');}
function render(){
if(view==='home')app.innerHTML=`<h1>Was möchten Sie erledigen?</h1><p class="muted">Wählen Sie einen Bereich aus.</p><div class="tiles">${[['houses','Häuser und Wohnungen','Mieterdaten und Wohnungen ansehen'],['payments','Mietzahlungen','Zahlungen eintragen und offene Mieten prüfen'],['bills','Rechnungen erfassen','Ausgaben einem Haus zuordnen'],['settlement','Nebenkosten abrechnen','Schritt für Schritt zur Beispielabrechnung']].map((t,i)=>`<button class="tile" data-go="${t[0]}"><span class="number">${i+1}</span><strong>${t[1]}</strong><span>${t[2]}</span></button>`).join('')}</div><div class="summary">${data.houses.length} Häuser · ${data.units.length} Wohnungen · Alle Bereiche enthalten Beispiele zum Ausprobieren.</div>`;
if(view==='houses')app.innerHTML=back()+`<h1>Ihre Häuser</h1><p>Wählen Sie das gewünschte Haus aus.</p>${data.houses.map(h=>`<div class="card row"><div><h2>${escape(h.name)}</h2><span>${escape(h.address)}</span><p class="muted">${data.units.filter(u=>u.house===h.id).length} Wohnungen</p></div><button data-house="${h.id}">Wohnungen ansehen</button></div>`).join('')}`;
if(view==='units')app.innerHTML=back('houses')+`<h1>${escape(house().name)}</h1><p>${escape(house().address)}</p>${data.units.filter(u=>u.house===houseId).map(u=>`<div class="card row"><div><h2>${escape(u.name)}</h2><p>${escape(u.tenant)} · ${u.area} m²</p><strong>${money(u.rent+u.advance)} monatlich</strong></div><button data-unit="${u.id}">Mieterdaten ansehen</button></div>`).join('')}`;
if(view==='tenant'){let u=unit();app.innerHTML=back('units')+`<h1>${escape(u.name)}</h1><div class="card"><h2>${escape(u.tenant)}</h2><div class="details"><p>Wohnfläche<br><strong>${u.area} m²</strong></p><p>Kaltmiete<br><strong>${money(u.rent)}</strong></p><p>Nebenkosten monatlich<br><strong>${money(u.advance)}</strong></p><p>Kaution vereinbart<br><strong>${money(u.deposit)}</strong></p></div></div><p class="muted">Die Mieterdaten sind in dieser ersten Vorschau nur zur Ansicht.</p>`;}
if(view==='payments')app.innerHTML=back()+`<h1>Mietzahlungen</h1><label for="month">Für welchen Monat?</label><input id="month" type="month" value="${month}"><div class="summary">Eingegangen: <strong>${money(data.units.reduce((s,u)=>s+paid(u),0))}</strong> · Noch offen: <strong>${money(data.units.reduce((s,u)=>s+Math.max(0,u.rent+u.advance-paid(u)),0))}</strong></div>${data.units.map(u=>{let p=paid(u),due=u.rent+u.advance,remaining=due-p;return `<div class="card"><div class="row"><div><h2>${escape(u.tenant)}</h2><p>${escape(data.houses.find(h=>h.id===u.house).name)} · ${escape(u.name)}</p></div><span class="status ${remaining<=0?'paid':''}">${remaining<0?'Überzahlung':remaining===0?'Bezahlt':p?'Teilweise bezahlt':'Offen'}</span></div><p>Fällig: ${money(due)} · Eingegangen: ${money(p)}</p><div class="row"><strong>${remaining<0?'Überzahlung: '+money(-remaining):'Noch offen: '+money(remaining)}</strong><button data-pay="${u.id}">Zahlung eintragen</button></div></div>`;}).join('')}`;
if(view==='pay')app.innerHTML=back('payments')+`<h1>Zahlung eintragen</h1><p>${escape(unit().tenant)} · ${month}</p><form id="payment-form" class="card"><label for="amount">Eingegangener Betrag in Euro</label><input id="amount" name="amount" type="number" step="0.01" min="0.01" max="1000000" required value="${Math.max(0,unit().rent+unit().advance-paid(unit()))||''}"><p>Tragen Sie nur diese zusätzliche Zahlung ein.</p><button class="primary" type="submit">Zahlung übernehmen</button></form>`;
if(view==='bills')app.innerHTML=back()+`<h1>Rechnungen erfassen</h1><form id="bill-form" class="card"><label for="bill-house">Zu welchem Haus gehört die Rechnung?</label><select id="bill-house" name="house">${options(data.houses,houseId)}</select><label for="kind">Kostenart</label><select id="kind" name="kind"><option>Wasserversorgung</option><option>Müllentsorgung</option><option>Gebäudereinigung</option><option>Versicherung</option><option>Reparatur</option></select><label for="date">Rechnungsdatum</label><input id="date" name="date" type="date" value="2026-09-15" required><label for="bill-amount">Betrag in Euro</label><input id="bill-amount" name="amount" type="number" min="0.01" max="1000000" step="0.01" required><div class="actions"><button class="primary">Rechnung übernehmen</button></div></form><h2>Erfasste Rechnungen</h2>${data.bills.slice().reverse().map(b=>`<div class="card row"><div><strong>${escape(b.kind)}</strong><br>${escape(data.houses.find(h=>h.id===b.house).name)} · ${escape(b.date)}</div><span class="amount">${money(b.amount)}</span></div>`).join('')}`;
if(view==='settlement'){const units=data.units.filter(u=>u.house===houseId);if(!units.some(u=>u.id===unitId))unitId=units[0].id;let bills=data.bills.filter(b=>b.house===houseId&&b.date.startsWith(String(year))&&b.kind!=='Reparatur'),total=bills.reduce((s,b)=>s+b.amount,0),area=units.reduce((s,u)=>s+u.area,0),share=Math.round(total*unit().area/area*100)/100;
app.innerHTML=back()+`<h1>Nebenkosten abrechnen</h1><p class="step">Schritt ${step} von 3</p>`+(step===1?`<div class="card"><h2>Haus und Wohnung auswählen</h2><label for="settle-house">Haus</label><select id="settle-house">${options(data.houses,houseId)}</select><label for="settle-unit">Wohnung</label><select id="settle-unit">${options(units,unitId)}</select><label for="year">Abrechnungsjahr</label><input id="year" type="number" min="2000" max="2100" value="${year}"><div class="actions"><button class="primary" data-step="2">Weiter zu den Kosten</button></div></div>`:step===2?`<div class="card"><h2>Kosten und Vorauszahlungen prüfen</h2><p>${escape(house().name)} · ${year}</p>${bills.length?bills.map(b=>`<p class="row"><span>${escape(b.kind)}</span><strong>${money(b.amount)}</strong></p>`).join(''):'<p>Für dieses Jahr sind noch keine Beispielkosten vorhanden.</p>'}<p class="row"><strong>Gesamtkosten</strong><strong>${money(total)}</strong></p><p>Beispielverteilung nach Wohnfläche: ${unit().area} von ${area} m². Anteil dieser Wohnung: <strong>${money(share)}</strong>.</p><label for="advance">Tatsächlich gezahlte Vorauszahlungen im Jahr (Euro)</label><input id="advance" type="number" min="0" max="1000000" step="0.01" value="${actualAdvance}"><p class="muted">Bitte für das Beispiel selbst eintragen. Aus einer Gesamtmietzahlung wird hier noch kein Nebenkostenanteil abgeleitet.</p><div class="actions"><button data-step="1">Zurück</button><button class="primary" data-step="3">Ergebnis ansehen</button></div></div>`:`<div class="card"><h2>Beispielabrechnung ${year}</h2><p>${escape(house().name)}<br>${escape(unit().name)} · ${escape(unit().tenant)}</p><p>Zeitraum: 01.01.${year} bis 31.12.${year}</p><table><thead><tr><th>Berechnung</th><th>Betrag</th></tr></thead><tbody><tr><td>Gesamtkosten des Hauses</td><td>${money(total)}</td></tr><tr><td>Wohnungsanteil (${unit().area} / ${area} m²)</td><td>${money(share)}</td></tr><tr><td>Gezahlte Vorauszahlungen</td><td>${money(actualAdvance)}</td></tr><tr><td><strong>${share>=actualAdvance?'Nachzahlung':'Guthaben'}</strong></td><td><strong>${money(Math.abs(share-actualAdvance))}</strong></td></tr></tbody></table><div class="actions"><button data-step="2">Angaben ändern</button><button class="primary" id="print">Drucken / als PDF speichern</button></div></div>`)+`<div class="summary"><strong>Nur eine Rechenvorschau.</strong> Alle hier einbezogenen Kosten werden vereinfacht nach Wohnfläche verteilt. Reparaturen sind ausgenommen. Heizkosten, Verbrauch, unterschiedliche Verteilerschlüssel und Mieterwechsel sind noch nicht umgesetzt. Diese Beispielabrechnung ist nicht zum Versand an Mieter bestimmt.</div>`;
}
}
document.getElementById('home').onclick=()=>go('home');document.getElementById('undo').onclick=()=>{if(history.length){data=history.pop();document.getElementById('undo').disabled=!history.length;document.getElementById('message').textContent='Letzte Änderung rückgängig gemacht.';render();}};
app.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.go){if(b.dataset.go==='settlement')step=1;go(b.dataset.go);}if(b.dataset.house){houseId=Number(b.dataset.house);go('units');}if(b.dataset.unit){unitId=Number(b.dataset.unit);go('tenant');}if(b.dataset.pay){unitId=Number(b.dataset.pay);go('pay');}if(b.dataset.step){let y=document.getElementById('year'),a=document.getElementById('advance');if(y){if(!y.value||!y.reportValidity())return;year=Number(y.value);}if(a){if(!a.value||!a.reportValidity())return;actualAdvance=Number(a.value);}step=Number(b.dataset.step);render();window.scrollTo(0,0);}if(b.id==='print')window.print();});
app.addEventListener('change',e=>{if(e.target.id==='month'&&e.target.value){month=e.target.value;render();}if(e.target.id==='settle-house'){houseId=Number(e.target.value);actualAdvance=0;render();}if(e.target.id==='settle-unit'){unitId=Number(e.target.value);actualAdvance=0;} });
app.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target),amount=Number(f.get('amount'));if(!Number.isFinite(amount)||amount<=0)return;save();if(e.target.id==='payment-form'){data.payments.push({unit:unitId,month,amount});go('payments');}if(e.target.id==='bill-form'){data.bills.push({house:Number(f.get('house')),date:String(f.get('date')),kind:String(f.get('kind')),amount});render();}});
render();
