'use strict';
const projectBacklogItems=[
{id:'cloud',title:'Zentrale Datenablage',status:'Noch offen',text:'Geschützte gemeinsame Büroablage einrichten. Die Demo speichert bisher nur auf diesem Browsergerät. Lokale Sicherungen und verschlüsselter Export sind vorhanden.'},
{id:'bank',title:'Echte Bankanbindung',status:'Noch offen',text:'Bankanbieter und Autorisierung einrichten. Demo-Umsätze und CSV-Abgleich sind bereits vorhanden.'},
{id:'tax',title:'Steuerberater-Schnittstelle abstimmen',status:'Noch offen',text:'Importformat und Kontenprofil mit der Kanzlei abstimmen. Strukturierte CSV-/ZIP-Exporte sind bereits vorhanden.'},
{id:'ocr',title:'Rechnungserkennung verbessern',status:'Vergleich geplant',text:'Lokale OCR ist vorhanden. Microsoft und Google mit typischen Rechnungen vergleichen. Automatische Hauszuordnung und gemerkte Korrekturen sind noch offen.'},
{id:'tenant',title:'Formular für neue Mieter',status:'Spätere Idee',text:'Kontakt-, Adress- und Bankdaten erfassen, Mietvertrag ansehen und herunterladen. Zugang gegebenenfalls per E-Mail oder WhatsApp bereitstellen. Noch nicht eingebaut; keine digitale Unterschrift vereinbart.'},
{id:'review',title:'Abrechnung vor echtem Einsatz fachlich prüfen',status:'Noch offen',text:'Nebenkostenberechnung und Sonderfälle fachlich prüfen. Heizkosten werden bislang als externe Dienstleisteranteile übernommen.'},
{id:'demo',title:'Verwalten und abrechnen',status:'In der Demo vorhanden',text:'Mieterwechsel mit Checklisten, Kautionen, Zahlungserinnerungen als PDF, Nebenkostenabrechnung, Vertragsablage, Statistik und Papierkorb. Lokale Sicherungen und verschlüsselter Export sind vorhanden.'}
];
function orderedBacklog(){const known=new Map(projectBacklogItems.map(x=>[x.id,x])),ids=[...new Set([...(Array.isArray(data.projectBacklogOrder)?data.projectBacklogOrder:[]),...known.keys()])];return ids.filter(id=>known.has(id)).map(id=>known.get(id));}
function reorderBacklog(id,target,after=false){const ids=orderedBacklog().map(x=>x.id);if(id===target||!ids.includes(id)||!ids.includes(target))return false;ids.splice(ids.indexOf(id),1);ids.splice(ids.indexOf(target)+(after?1:0),0,id);save();data.projectBacklogOrder=ids;persistData();return true;}
function compactBacklog(){const rows=orderedBacklog();return `<p>Oben steht die höchste Priorität. Am Griff ziehen, um die Reihenfolge zu ändern. Die Reihenfolge wird in diesem Browser gespeichert.</p><div id="backlog-list">${rows.map((item,i)=>`<div class="backlog-line" data-backlog-id="${item.id}"><button type="button" class="backlog-grip" draggable="true" data-backlog-drag="${item.id}" aria-label="${escape(item.title)} ziehen" title="Zum Sortieren ziehen">⠿</button><span class="backlog-rank">${i+1}</span><details><summary><strong>${escape(item.title)}</strong><span class="backlog-status">${escape(item.status)}</span></summary><p>${escape(item.text)}</p></details></div>`).join('')}</div><p id="backlog-feedback" role="status"></p>`;}
function setupCompactBacklog(portal){let dragged='';const refresh=id=>{const open=new Set([...portal.querySelectorAll('.backlog-line')].filter(el=>el.querySelector('details').open).map(el=>el.dataset.backlogId));portal.querySelector('#compact-backlog').innerHTML=compactBacklog();for(const el of portal.querySelectorAll('.backlog-line'))if(open.has(el.dataset.backlogId))el.querySelector('details').open=true;portal.querySelector('#backlog-feedback').textContent='Priorität geändert.';portal.querySelector(`[data-backlog-drag="${id}"]`)?.focus();};portal.addEventListener('click',e=>{const b=e.target.closest('[data-backlog-move]');if(!b)return;const rows=orderedBacklog(),i=rows.findIndex(x=>x.id===b.dataset.backlogMove),down=b.dataset.direction==='down',target=rows[i+(down?1:-1)];if(target&&reorderBacklog(rows[i].id,target.id,down))refresh(rows[i].id);});portal.addEventListener('dragstart',e=>{const h=e.target.closest('[data-backlog-drag]');if(!h)return;dragged=h.dataset.backlogDrag;e.dataTransfer.setData('text/plain',dragged);e.dataTransfer.effectAllowed='move';});portal.addEventListener('dragover',e=>{if(!dragged)return;const row=e.target.closest('[data-backlog-id]');if(!row)return;e.preventDefault();e.dataTransfer.dropEffect='move';for(const el of portal.querySelectorAll('.backlog-drop'))el.classList.remove('backlog-drop');row.classList.add('backlog-drop');});portal.addEventListener('drop',e=>{const row=e.target.closest('[data-backlog-id]');if(!dragged||!row)return;e.preventDefault();const id=dragged,after=e.clientY>row.getBoundingClientRect().top+row.getBoundingClientRect().height/2;dragged='';if(reorderBacklog(id,row.dataset.backlogId,after))refresh(id);for(const el of portal.querySelectorAll('.backlog-drop'))el.classList.remove('backlog-drop');});portal.addEventListener('dragend',()=>{dragged='';for(const el of portal.querySelectorAll('.backlog-drop'))el.classList.remove('backlog-drop');});}
