'use strict';
function icon(name) {
  const paths={houses:'M3 21V9l9-6 9 6v12H3Zm6 0v-8h6v8M7 10h.01M17 10h.01',payments:'M3 6h18v14H3V6Zm0 4h18M7 15h3M16 3H6v3',bills:'M6 3h12v18l-3-2-3 2-3-2-3 2V3Zm3 5h6M9 12h6',settlement:'M5 3h14v18H5V3Zm3 4h8M8 12h2M14 12h2M8 16h2M14 16h2',dashboard:'M4 20V10h4v10M10 20V4h4v16M16 20v-7h4v7M3 20h18'};
  return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.houses}"/></svg>`;
}
let statsHouse=0;
function statistics(selectedMonth=month,selectedHouse=statsHouse){
  const units=data.units.filter(u=>!selectedHouse||u.house===selectedHouse);
  const received=u=>data.payments.filter(p=>p.unit===u.id&&p.month===selectedMonth).reduce((s,p)=>s+p.amount,0);
  const bills=data.bills.filter(b=>(!selectedHouse||b.house===selectedHouse)&&b.date.slice(0,7)===selectedMonth);
  return {units,bills,due:units.reduce((s,u)=>s+u.rent+u.advance,0),income:units.reduce((s,u)=>s+received(u),0),open:units.reduce((s,u)=>s+Math.max(0,u.rent+u.advance-received(u)),0),over:units.reduce((s,u)=>s+Math.max(0,received(u)-u.rent-u.advance),0),covered:units.reduce((s,u)=>s+Math.min(received(u),u.rent+u.advance),0),expenses:bills.reduce((s,b)=>s+b.amount,0)};
}
function bar(label,value,max,tone='blue',formatted=money(value)) {return `<div class="chart-row"><div class="row"><span>${escape(label)}</span><strong>${formatted}</strong></div><div class="bar-track" aria-hidden="true"><span class="bar-fill ${tone}" style="width:${max?Math.min(100,Math.max(0,value/max*100)):0}%"></span></div></div>`;}
function dashboard(){
 const s=statistics(),dateLabel=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(new Date(month+'-01T12:00:00')),coverage=s.due?Math.round(s.covered/s.due*100):0;
 const houseRows=data.houses.filter(h=>!statsHouse||h.id===statsHouse).map(h=>({h,s:statistics(month,h.id)}));
 const costGroups=Object.entries(s.bills.reduce((a,b)=>{a[b.kind]=(a[b.kind]||0)+b.amount;return a},{}));
 return back()+`<div class="section-heading"><span class="section-icon">${icon('dashboard')}</span><div><span class="eyebrow">ZAHLEN IM BLICK</span><h1>Statistik-Dashboard</h1></div></div><p class="muted">Mietzahlungen und erfasste Rechnungen für ${dateLabel}.</p><div class="filter-panel"><div><label for="month">Monat</label><input id="month" type="month" value="${month}"></div><div><label for="stats-house">Haus</label><select id="stats-house"><option value="0">Alle Häuser</option>${options(data.houses,statsHouse)}</select></div></div><div class="kpi-grid">${[['payments','Mieteingänge',money(s.income),'Einschließlich Nebenkostenvorauszahlungen','teal'],['bills','Offene Mieten',money(s.open),'Für den ausgewählten Monat','amber'],['settlement','Erfasste Ausgaben',money(s.expenses),'Nach Rechnungsdatum, nicht Zahlungsdatum','blue'],['houses','Wohneinheiten',s.units.length,`${s.units.reduce((a,u)=>a+u.area,0)} m² Wohnfläche`,'purple']].map(([i,label,value,note,tone])=>`<section class="kpi ${tone}"><span class="kpi-icon">${icon(i)}</span><h2>${label}</h2><strong class="kpi-value">${value}</strong><p>${note}</p></section>`).join('')}</div><div class="dashboard-grid"><section class="card"><div class="row"><h2>Zahlungsstand</h2><span class="status ${coverage===100?'paid':''}">${coverage} % gedeckt</span></div><p>Monatlich fällig: <strong>${money(s.due)}</strong></p>${bar('Durch Zahlungen gedeckt',s.covered,s.due,'teal')}${bar('Noch offen',s.open,s.due,'amber')}${s.over?`<p>Zusätzliche Überzahlungen: <strong>${money(s.over)}</strong></p>`:''}<button data-go="payments">Mietzahlungen ansehen</button></section><section class="card"><h2>Ausgaben nach Kostenart</h2><p class="muted">Erfasste Rechnungen in ${dateLabel}</p>${costGroups.length?costGroups.map(([k,v])=>bar(k,v,Math.max(...costGroups.map(x=>x[1])))).join(''):`<div class="empty-chart">${icon('bills')}<strong>Keine Rechnungen erfasst</strong><p>Für diesen Monat sind noch keine Ausgaben eingetragen.</p></div>`}<button data-go="bills">Rechnung erfassen</button></section><section class="card house-comparison"><h2>Mieteingänge je Haus</h2><p class="muted">Einheitlicher Maßstab für den direkten Vergleich.</p>${houseRows.map(({h,s:hs})=>`<div class="house-chart">${bar(h.name,hs.income,Math.max(...houseRows.map(x=>Math.max(x.s.income,x.s.due))), 'teal')}<p class="chart-note">Fällig: ${money(hs.due)} · Offen: ${money(hs.open)}${hs.over?' · Überzahlung: '+money(hs.over):''}</p></div>`).join('')}</section></div><p class="data-note">Die Statistik verwendet die Beispieldaten und Ihre Eingaben dieser Sitzung. Offene Beträge gelten nur für den gewählten Monat; Rechnungsbeträge sind keine bestätigten Geldabflüsse.</p>`;
}
