'use strict';
function createDemo(){
 const d={version:2,houses:[{id:1,name:'Haus am Park',address:'Beispielstraße 12 · Nürnberg'},{id:2,name:'Haus an der Linde',address:'Musterweg 8 · Fürth'},{id:3,name:'Haus am Stadtgarten',address:'Demoweg 24 · Erlangen'}],units:[],payments:[],bills:[],contracts:[]};
 const names=['Erika Beispiel','Karl Mustermann','Maria Muster','Paul Beispiel','Anna Musterfrau','Thomas Beispiel','Clara Muster','Jonas Mustermann','Lena Beispiel','Peter Muster','Sophie Beispiel','Max Mustermann','Hannah Muster','Felix Beispiel','Emma Musterfrau','Leon Beispiel','Mia Muster','Otto Beispiel','Laura Mustermann','Ben Muster'];
 names.forEach((tenant,i)=>{const id=i+1,house=i<7?1:i<14?2:3,n=i-(house===1?0:house===2?7:14)+1,area=48+(i*7)%53,rent=area*11,advance=150+(i%5)*20;d.units.push({id,house,name:`Wohnung ${String(n).padStart(2,'0')} · ${n<=2?'Erdgeschoss':Math.ceil(n/2)-1+'. Obergeschoss'}`,area,tenant,rent,advance,deposit:rent*3,start:'2024-01-01',email:`mieter${id}@example.invalid`});});
 for(const y of [2025,2026])for(let m=1;m<=(y===2025?12:9);m++)for(const u of d.units){const month=`${y}-${String(m).padStart(2,'0')}`;if(y===2026&&m===9&&u.id===20)continue;const partial=y===2026&&m===9&&u.id===8,over=y===2026&&m===9&&u.id===3?50:0;const rentPart=partial?Math.round(u.rent/2):u.rent,nkPart=partial?Math.round(u.advance/2):u.advance;d.payments.push({id:`MI-${month}-${u.id}`,unit:u.id,month,date:`${month}-03`,amount:rentPart+nkPart+over,rentPart,nkPart,unallocated:over,reference:`Miete ${month} / Wohnung ${u.id}`});}
 for(const y of [2025,2026])for(let m=1;m<=(y===2025?12:9);m++)for(const h of d.houses){const period=`${y}-${String(m).padStart(2,'0')}`;for(const [k,kind,base,vendor] of [['EN','Energieversorgung',420,'Demo Stadtenergie'],['WA','Wasserversorgung',135,'Demo Wasserwerke'],['RE','Gebäudereinigung',180,'Demo Hausservice']])d.bills.push({id:`RE-${h.id}-${period}-${k}`,house:h.id,date:`${period}-10`,paidDate:`${period}-15`,kind,amount:base+h.id*25,vendor,reference:`${k}-${h.id}-${period}`,document:null});if(m===1)d.bills.push({id:`RE-${h.id}-${y}-VS`,house:h.id,date:`${y}-01-08`,paidDate:`${y}-01-12`,kind:'Versicherung',amount:900+h.id*120,vendor:'Demo Gebäudeversicherung',reference:`VS-${h.id}-${y}`,document:null});if(m===6)d.bills.push({id:`RE-${h.id}-${y}-REP`,house:h.id,date:`${y}-06-20`,paidDate:`${y}-07-02`,kind:'Reparatur',amount:350+h.id*90,vendor:'Demo Handwerksbetrieb',reference:`REP-${h.id}-${y}`,document:null});}
 for(const h of d.houses)for(const [type,provider,amount] of [['Versicherung','Demo Gebäudeversicherung',900+h.id*120],['Versorger','Demo Stadtenergie',(420+h.id*25)*12],['Versorger','Demo Wasserwerke',(135+h.id*25)*12]]){const id=`V-${h.id}-${d.contracts.length+1}`,text=`DEMO-DOKUMENT – KEIN ECHTER VERTRAG\n\n${type}: ${provider}\nObjekt: ${h.name}\nVertragsnummer: ${id}\nBeginn: 01.01.2025\nEnde: 31.12.2026\nJahresbetrag: ${amount.toFixed(2)} EUR\n\nErfundene Vertragsdaten ausschließlich zum Testen der Ablage.\n`;d.contracts.push({id,house:h.id,type,provider,number:id,start:'2025-01-01',end:'2026-12-31',notice:'3 Monate vor Laufzeitende (Demo)',amount,note:'Erfundener Mustervertrag zur Demonstration.',document:{name:id+'.txt',blob:new Blob([text],{type:'text/plain;charset=utf-8'})}});}
 for(const b of d.bills)b.document={name:b.id+'.txt',blob:new Blob([`DEMO-BELEG – KEINE ECHTE RECHNUNG\nBeleg-ID: ${b.id}\nAussteller: ${b.vendor}\nRechnungsnummer: ${b.reference}\nRechnungsdatum: ${b.date}\nZahlungsdatum: ${b.paidDate}\nKostenart: ${b.kind}\nBruttobetrag: ${b.amount.toFixed(2)} EUR\nHaus-ID: ${b.house}\nUmsatzsteuer: nicht ausgewiesen / fachlich ungeprüft.\n`],{type:'text/plain;charset=utf-8'})};
 return d;
}
