'use strict';
function exportProfilePage(){const p=data.exportProfile,kinds=[...new Set(data.bills.map(b=>b.kind))];return `<details class="card"><summary>Kanzlei-Export vorbereiten</summary><p>Zusätzliche Buchungsvorschläge im neutralen CSV-Format. Kein fertiger DATEV-Import: Format und Konten müssen mit Ihrer Kanzlei abgestimmt werden. Kein automatischer Versand.</p><form id="export-profile"><label>Kanzlei / Profilname<input name="name" value="${escape(p.name)}"></label><label>Mandantenkennung<input name="mandate" value="${escape(p.mandate)}"></label><label>Geldkonto (nach Kanzleivorgabe)<input name="bank" value="${escape(p.bank||'')}" pattern="[0-9]{3,10}"></label>${[['Kaltmiete','Kaltmiete'],['Nebenkosten','Nebenkostenvorauszahlungen'],...kinds.map(k=>[k,k])].map(([k,label],i)=>`<label>${escape(label)} – Sachkonto<input name="account-${i}" value="${escape(p.accounts[k]||'')}" pattern="[0-9]{3,10}"></label>`).join('')}<button>Exportprofil speichern</button></form></details>`;}
function setupExportProfile(){const previous=exportFiles;exportFiles=function(){const files=previous(),t=taxData(),profile=data.exportProfile,known=new Set(t.units.map(u=>u.id)),leaseName=p=>leaseForPayment(p)?.tenant||'Zuordnung offen';const replace=(name,rows)=>{const f=files.find(f=>f.name===name);if(f)f.body=csv(rows);else files.push({name,body:csv(rows)})};
replace('01_Mieteingaenge.csv',[['Zahlungs_ID','Zahlungstag','Mietmonat','Haus_ID','Wohnung_ID','Mietverhaeltnis_ID','Mieter','Gesamt_EUR','Kaltmiete_EUR','Nebenkosten_EUR','Ungeklaert_EUR','Referenz'],...t.payments.map(p=>[p.id,p.date,p.month,String(data.units.find(u=>u.id===p.unit).house),String(p.unit),p.leaseId||'',leaseName(p),p.amount,p.rentPart||0,p.nkPart||0,p.unallocated||0,p.reference||''])]);
const accountRows=[['Bewegungs_ID','Datum','Mandant','Wohnung_ID','Text','Betrag_EUR','Richtung','Sachkonto_Vorschlag','Geldkonto_Vorschlag','Beleg_ID','Status']];for(const p of t.payments)for(const [key,value]of [['Kaltmiete',p.rentPart||0],['Nebenkosten',p.nkPart||0],['Ungeklaert',p.unallocated||0]])if(value)accountRows.push([p.id+'-'+key,p.date,profile.mandate,String(p.unit),key+' '+leaseName(p),value,'Eingang',profile.accounts[key]||'',profile.bank||'',p.id,'Mit Kanzlei pruefen']);for(const b of t.paidBills)accountRows.push([b.id,b.paidDate,profile.mandate,'',b.kind,b.amount,'Ausgang',profile.accounts[b.kind]||'',profile.bank||'',b.id,'Mit Kanzlei pruefen']);replace('07_Buchungsvorschlaege.csv',accountRows);
const deposits=data.depositMovements.filter(r=>r.date.startsWith(String(taxYear))&&known.has(data.leases.find(l=>l.id===r.leaseId)?.unit));replace('08_Kautionsbewegungen.csv',[['ID','Datum','Mietverhaeltnis_ID','Mieter','Art','Betrag_EUR','Vermerk','Belegdatei'],...deposits.map(r=>[r.id,r.date,r.leaseId,data.leases.find(l=>l.id===r.leaseId)?.tenant||'',r.type==='in'?'Eingang':r.type==='out'?'Rueckzahlung':'Einbehalt',r.amount,r.note,r.document?`Kautionsbelege/${safeName(r.id)}-${safeName(r.document.name)}`:''])]);for(const r of deposits)if(r.document)files.push({name:`Kautionsbelege/${safeName(r.id)}-${safeName(r.document.name)}`,body:r.document.blob});
const rentRows=[['Haus_ID','Wohnung_ID','Mietverhaeltnis_ID','Mieter','Mietmonat','Soll_EUR','Zugeordnet_EUR','Offen_EUR','Ueberzahlung_EUR']];for(let m=1;m<=(taxYear===2026?9:12);m++){const mo=taxYear+'-'+String(m).padStart(2,'0');for(const l of data.leases.filter(l=>known.has(l.unit)&&leaseDue(l,mo).days)){const d=leaseDue(l,mo),due=d.rent+d.advance,paid=paidForLease(l,mo);rentRows.push([String(data.units.find(u=>u.id===l.unit).house),String(l.unit),l.id,l.tenant,mo,due,paid,Math.max(0,eur(cents(due)-cents(paid))),Math.max(0,eur(cents(paid)-cents(due)))]);}}replace('04_Mietkonten.csv',rentRows);
replace('09_Mietverhaeltnisse.csv',[['ID','Wohnung_ID','Mieter','Einzug','Auszug','Kaltmiete_EUR','Nebenkosten_EUR','Kaution_vereinbart_EUR'],...data.leases.filter(l=>known.has(l.unit)).map(l=>[l.id,String(l.unit),l.tenant,l.start,l.end,l.rent,l.advance,l.deposit])]);files.find(f=>f.name==='BITTE_LESEN.txt').body+='\n\nErweiterung: Buchungsvorschläge nutzen nur manuell eingetragene Kanzleikonten. Nicht zugeordnete Konten bleiben leer. Kautionen sind separat und werden nicht zu Mietzahlungen addiert. Einbehalte sind zu prüfen und keine automatisch erzeugten Ertragsbuchungen. Mietkonten berücksichtigen Ein- und Auszüge nach Kalendertagen.\n';return files;};
app.addEventListener('submit',e=>{if(e.target.id!=='export-profile')return;e.preventDefault();const f=new FormData(e.target),kinds=['Kaltmiete','Nebenkosten',...new Set(data.bills.map(b=>b.kind))];save();data.exportProfile={name:String(f.get('name')),mandate:String(f.get('mandate')),bank:String(f.get('bank')),accounts:Object.fromEntries(kinds.map((k,i)=>[k,String(f.get('account-'+i)||'')]))};render();});}
