'use strict';
const cents=n=>Math.round(Number(n)*100),eur=n=>n/100,todayISO=()=>new Date().toISOString().slice(0,10);
const DAY=86400000,dayNumber=s=>Date.parse(s+'T00:00:00Z')/DAY;
function validDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(dayNumber(s))&&new Date(dayNumber(s)*DAY).toISOString().slice(0,10)===s;}
function daysBetween(a,b){return Math.max(0,dayNumber(b)-dayNumber(a)+1);}
function monthBounds(m){const [y,n]=m.split('-').map(Number);return [m+'-01',new Date(Date.UTC(y,n,0)).toISOString().slice(0,10)];}
function periodOverlap(a,b,c,d){return daysBetween(a>c?a:c,b<d?b:d);}
function enhanceData(){
 data.leases??=data.units.map(u=>({id:'L-'+u.id,unit:u.id,tenant:u.tenant,email:u.email||'',start:u.start||'2024-01-01',end:'',rent:u.rent,advance:u.advance,deposit:u.deposit}));
 for(const p of data.payments)if(!p.leaseId){const ls=data.leases.filter(l=>l.unit===p.unit&&l.start<=(p.month+'-31')&&(!l.end||l.end>=p.month+'-01'));if(ls.length===1)p.leaseId=ls[0].id;}
 data.depositMovements??=data.leases.map(l=>({id:'K-DEMO-'+l.id,leaseId:l.id,type:'in',amount:l.deposit,date:l.start,note:'Erfundener Demo-Kautionseingang',document:null}));
 data.checklistTemplates??={in:['Mietvertrag unterschrieben ablegen','Kautionszahlung prüfen','Übergabetermin vereinbaren','Wohnungszustand und Fotos dokumentieren','Zählerstände aufnehmen','Schlüsselanzahl und Übergabe dokumentieren','Kontaktdaten und Namensschild prüfen'],out:['Auszugsdatum und Übergabetermin bestätigen','Wohnungszustand und Fotos dokumentieren','Zählerstände aufnehmen','Schlüssel vollständig zurücknehmen','Nachsendeadresse erfassen','Offene Zahlungen und Kaution prüfen','Abschlussabrechnung vorbereiten']};
 data.checklists??={};data.settlements??={};data.bankItems??=[];data.exportProfile??={name:'',mandate:'',accounts:{}};
 for(const c of data.contracts)if(c.deadline===undefined)c.deadline=c.id.startsWith('V-')&&c.note==='Erfundener Mustervertrag zur Demonstration.'?'2026-09-30':'';
 data.tenants??=[];
 for(const l of data.leases){if(!l.tenantId){l.tenantId='T-'+l.id;}if(!data.tenants.some(t=>t.id===l.tenantId))data.tenants.push({id:l.tenantId,name:l.tenant,email:l.email||'',phone:'',address:''});}
 data.enhancedVersion=1;
}
function leasesInMonth(unit,m){const [a,b]=monthBounds(m);return data.leases.filter(l=>l.unit===unit&&periodOverlap(l.start,l.end||'9999-12-31',a,b)>0);}
function leaseRateAt(l,date){return (l.rateChanges||[]).filter(x=>x.from<=date).sort((a,b)=>b.from.localeCompare(a.from))[0]||{rent:l.rent,advance:l.advance};}
function addRentChange(id,values){const l=data.leases.find(l=>l.id===id),from=String(values.from||''),rent=Number(values.rent),advance=Number(values.advance);if(!l||!validDate(from)||from<=l.start||l.end&&from>l.end)throw new Error('Gültigkeitsdatum muss nach dem Einzug und innerhalb des Mietzeitraums liegen.');if(![rent,advance].every(n=>Number.isFinite(n)&&n>=0&&n<=10000000))throw new Error('Bitte gültige positive Beträge oder null eingeben.');if((l.rateChanges||[]).some(x=>x.from===from))throw new Error('Für dieses Datum besteht bereits eine Mietänderung.');save();(l.rateChanges??=[]).push({from,rent,advance});l.rateChanges.sort((a,b)=>a.from.localeCompare(b.from));}
function leaseDue(l,m){const [a,b]=monthBounds(m),n=periodOverlap(l.start,l.end||'9999-12-31',a,b),total=daysBetween(a,b);let rent=0,advance=0;for(let day=Math.max(dayNumber(a),dayNumber(l.start));day<=Math.min(dayNumber(b),dayNumber(l.end||'9999-12-31'));day++){const rate=leaseRateAt(l,new Date(day*DAY).toISOString().slice(0,10));rent+=cents(rate.rent);advance+=cents(rate.advance);}return {rent:eur(Math.round(rent/total)),advance:eur(Math.round(advance/total)),days:n};}
function dueForUnit(u,m){return amountSum(leasesInMonth(u.id,m),l=>{const d=leaseDue(l,m);return d.rent+d.advance});}
function leaseForPayment(p){return data.leases.find(l=>l.id===p.leaseId);}
function paidForLease(l,m){return amountSum(data.payments.filter(p=>p.leaseId===l.id&&p.month===m));}
function depositBalance(l){const rows=data.depositMovements.filter(r=>r.leaseId===l.id),received=amountSum(rows.filter(r=>r.type==='in')),returned=amountSum(rows.filter(r=>r.type==='out')),retained=amountSum(rows.filter(r=>r.type==='retained'));return {received,returned,retained,held:eur(cents(received)-cents(returned)-cents(retained)),open:Math.max(0,eur(cents(l.deposit)-cents(received)))};}
function validateLease(l,ignoreId=''){const issues=[];if(!String(l.tenant).trim())issues.push('Bitte den Namen eintragen.');if(!validDate(l.start)||l.end&&!validDate(l.end)||l.end&&l.end<l.start)issues.push('Bitte gültige Ein- und Auszugsdaten prüfen.');if(!data.units.some(u=>u.id===l.unit))issues.push('Wohnung fehlt.');for(const k of ['rent','advance','deposit'])if(!Number.isFinite(l[k])||l[k]<0)issues.push('Beträge müssen null oder positiv sein.');if(data.leases.some(x=>x.id!==ignoreId&&x.unit===l.unit&&periodOverlap(x.start,x.end||'9999-12-31',l.start,l.end||'9999-12-31')>0))issues.push('Dieser Zeitraum überschneidet sich mit einem vorhandenen Mietverhältnis.');return issues;}
function refreshUnitNames(){for(const u of data.units){const l=data.leases.find(l=>l.unit===u.id&&(l.actualStartUnknown||l.start<=todayISO())&&(!l.end||l.end>=todayISO()));u.tenant=l?.tenant||'Leerstand';if(l){const rate=leaseRateAt(l,todayISO());u.rent=rate.rent;u.advance=rate.advance;u.deposit=l.deposit;u.start=l.start;u.email=l.email;}}}
function splitCents(total,weights){const sum=weights.reduce((a,b)=>a+b,0);if(sum<=0)return weights.map(()=>0);const raw=weights.map(w=>total*w/sum),out=raw.map(Math.floor);let rest=total-out.reduce((a,b)=>a+b,0);const order=raw.map((r,i)=>({i,f:r-out[i]})).sort((a,b)=>b.f-a.f||a.i-b.i);for(let j=0;j<rest;j++)out[order[j%order.length].i]++;return out;}
function settlementSegments(h,y){const from=y+'-01-01',to=y+'-12-31',segments=[];for(const u of data.units.filter(u=>u.house===h)){const ls=data.leases.filter(l=>l.unit===u.id&&periodOverlap(l.start,l.end||'9999-12-31',from,to)>0).sort((a,b)=>a.start.localeCompare(b.start));let cursor=from;const next=s=>new Date((dayNumber(s)+1)*DAY).toISOString().slice(0,10),prev=s=>new Date((dayNumber(s)-1)*DAY).toISOString().slice(0,10);for(const l of ls){const a=l.start>from?l.start:from,b=l.end&&l.end<to?l.end:to;if(a>cursor)segments.push({id:'vac-'+u.id+'-'+cursor,unit:u.id,area:u.area,tenant:'Eigentümer / Leerstand',from:cursor,to:prev(a),vacant:true});segments.push({id:l.id,unit:u.id,area:u.area,tenant:l.tenant,from:a,to:b,vacant:false});if(next(b)>cursor)cursor=next(b);}if(cursor<=to)segments.push({id:'vac-'+u.id+'-'+cursor,unit:u.id,area:u.area,tenant:'Eigentümer / Leerstand',from:cursor,to,vacant:true});}return segments.map(s=>({...s,days:daysBetween(s.from,s.to)}));}

function tenantPaymentStatistics(l,asOf=todayISO()){const payments=data.payments.filter(p=>p.leaseId===l.id&&validDate(p.date)&&p.date<=asOf),byMonth=new Map();for(const p of payments)byMonth.set(p.month,(byMonth.get(p.month)||0)+cents(p.amount));let months=0,paidMonths=0,due=0;const end=l.end&&l.end<asOf?l.end:asOf;if(validDate(l.start)&&end>=l.start){let [y,m]=l.start.slice(0,7).split('-').map(Number);while(y+'-'+String(m).padStart(2,'0')<=end.slice(0,7)){const key=y+'-'+String(m).padStart(2,'0'),d=leaseDue(l,key),owed=cents(d.rent)+cents(d.advance);if(d.days){months++;due+=owed;if(owed>0&&(byMonth.get(key)||0)>=owed)paidMonths++;}m++;if(m===13){m=1;y++;}}}return {received:amountSum(payments),paymentCount:payments.filter(p=>p.amount>0).length,paidMonths,months,due:eur(due)};}
