'use strict';
(() => {
const portal=document.getElementById('portal'),shell=document.getElementById('app-shell');let signedIn=false;
const brand=`<div class="portal-brand"><img src="assets/logo.svg" width="88" height="88" alt="Bayers Immobilien Chaos Logo"><p class="eyebrow">BAYERS IMMOBILIEN</p><h1>Chaos? Mit Übersicht.</h1><p>Bayers Immobilien Chaos Webseite</p></div>`;
function showLogin(){signedIn=false;shell.hidden=true;portal.hidden=false;portal.innerHTML=`${brand}<form id="demo-login" class="card login-card"><span class="status">Demo-Zugang</span><h2>Willkommen zurück</h2><p>Erst anmelden, dann den Projektstand ansehen und die Verwaltung öffnen.</p><label>Demo-Passwort<input name="password" type="password" autocomplete="off" required aria-describedby="demo-hint"></label><p id="demo-hint">Bitte das vereinbarte Demo-Passwort eingeben.</p><button class="primary">Anmelden</button><p id="login-error" role="alert"></p><p class="muted">Dieser Demo-Login bietet keinen Zugangsschutz. Bitte keine echten Zugangsdaten oder Mieterdaten verwenden.</p></form>`;window.scrollTo(0,0);}
function showOverview(){if(!signedIn){showLogin();return;}shell.hidden=true;portal.hidden=false;portal.innerHTML=`${brand}<div class="portal-top"><h2>Deine Projektübersicht</h2><button data-portal-action="logout">Abmelden</button></div><section class="card release-card"><div><span class="status">Aktuelle Demoversion · 15.09.2026</span><h2>Die Hausverwaltung ausprobieren</h2><p>Häuser und Wohnungen anlegen, Mieten prüfen, Belege und Verträge verwalten.</p><ul><li>Neue Kurzübersicht und 24-Monats-Grafik bei Mietzahlungen</li><li>Vertragsarten filtern und Kündigungstermine direkt am Vertrag pflegen</li><li>Senioren- und Standard-Version jederzeit umschalten</li><li>Papierkorb mit 90 Tagen Aufbewahrung</li></ul></div><button class="primary" data-portal-action="launch">Aktuelle Version öffnen →</button></section><section><h2>Backlog &amp; Projektstand</h2><p>Was bereits ausprobiert werden kann und was als Nächstes vorbereitet wird.</p><div id="compact-backlog">${compactBacklog()}</div><details class="card"><summary>Bewusst nicht eingeplant</summary><p>Individuelle Rollenverwaltung, allgemeines Team-Aufgabenboard und Dokumentenversionierung.</p></details></section><p class="muted">Öffentliche Vorschau mit erfundenen Beispieldaten. Demo-Anmeldung ohne echten Zugangsschutz. Fachliche Produktionsprüfung der Abrechnung und externe Anschlüsse stehen noch aus.</p>`;window.scrollTo(0,0);}
portal.addEventListener('submit',async e=>{if(e.target.id!=='demo-login')return;e.preventDefault();const f=new FormData(e.target);if(Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(f.get('password')))))).map(x=>x.toString(16).padStart(2,'0')).join('')!=='4479c6502e3b4be1bd2afd525b3d6ddb03c13b9ad96c4e97b05cba957682123d'){document.getElementById('login-error').textContent='Das Demo-Passwort stimmt nicht.';return;}signedIn=true;showOverview();});
portal.addEventListener('click',e=>{const b=e.target.closest('[data-portal-action]');if(!b)return;if(b.dataset.portalAction==='logout')showLogin();if(b.dataset.portalAction==='launch'&&signedIn){portal.hidden=true;shell.hidden=false;window.scrollTo(0,0);}});
document.getElementById('project-overview').addEventListener('click',showOverview);document.getElementById('demo-logout').addEventListener('click',showLogin);setupCompactBacklog(portal);showLogin();
})();
